apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio1
  template:
    metadata:
      labels:
        app: portfolio1
    spec:
      containers:
      - name: portfolio1
        image: gcr.io/operating-tiger-428509-v6/portfolio1:latest
        ports:
        - containerPort: 80